### PR TITLE
[OGUI-661] Add Readout URI input field

### PR DESCRIPTION
**Pull request by graduta**
* Adds a text input field in the Basic Configuration panel so that the user can easily add the path to the readout configuration file. This field will send to core the value under the key `readout_cfg_uri`
* Changes name of "Templates" to "Workflow" Panel
* Bumps patch version

### CODE REVIEW

**Review by awegrzyn — COMMENTED** [review]
URI syntax requires to have scheme specified (eg.: `file://`) ? If scheme does not need to be specified I'd call it `Readout (file) path`.

**Comment by graduta** [comment]
> URI syntax requires to have scheme specified (eg.: `file://`) ? If scheme does not need to be specified I'd call it `Readout (file) path`.

I believe it has to be in that format but I cannot tell only from the documentation: https://github.com/AliceO2Group/ControlWorkflows 

@vascobarroso would you happen to know more about this?

**Comment by awegrzyn** [comment]
Ok, in such case maybe you could hardcode `file://` before input box? It would be more straightforward.

**Comment by vascobarroso** [comment]
It doesn't need to be a path to a file, it can be a Consul endpoint (`consul://path/to/config`). Therefore, I think `Readout URI` or maybe `Readout Config URI` are good labels.

**Comment by vascobarroso** [comment]
> Ok, in such case maybe you could hardcode `file://` before input box? It would be more straightforward.

That's probably not a bad idea, but then it should be a dropdown to select between `file://` and `consul://`.

**Comment by awegrzyn** [comment]
All right, so in such case we either leave it as it is or add a drop down menu with `file://` and `consul://`

**Comment by graduta** [comment]
> All right, so in such case we either leave it as it is or add a drop down menu with `file://` and `consul://`
Added a dropdown to allow the user to specify the type of path: `consul:\\` or `file:\\`
If no path will be provided in the input text field than no variable will be sent to AliECS
image

**Review by awegrzyn — APPROVED** [review]

**Pull request merged**
