### PR TITLE
Use new, simpler, API (QC-368)

### PR DESCRIPTION
**Pull request by Barthelemy**
#### I DON'T have JIRA ticket
- [ ] explain what this PR does
- [ ] if it is new feature explain how plan to use it
- [ ] test are added
- [ ] documentation is changed or added

#### I have JIRA issue created
- [x] branch and/or PR name(s) includes JIRA ID
- [ ] issue has "Fix version" assigned
- [ ] issue "Status" is set to "In review"
- [ ] PR labels are selected

### CODE REVIEW

**Comment by Barthelemy** [comment]
The former interface is still available in case of problems.

**Comment by graduta** [comment]
@Barthelemy Could you please link in the description to the PR on the QualityControl side containing related changes and also to alidist PR with the version bump

**Comment by Barthelemy** [comment]
The change in QC has happened in April and thus the versions of QC and QCG do not need to be synchronized. In other words, QC v1.0 already contains the necessary changes. 

FYI it was part of a massive overhaul of the CCDB API and storage format (https://alice.its.cern.ch/jira/browse/QC-239).

**Comment by graduta** [comment]
Will keep this PR open for a bit more. This is due to the fact that we are currently investigating the possibility of requesting objects data and files directly from CCDB

**Pull request merged**
