### PR TITLE
[OGUI-823] Add panel in environment page with selected user vars

### PR DESCRIPTION
**Pull request by graduta**
#### I have JIRA issue created
- [x] branch and/or PR name(s) includes JIRA ID
- [x] issue has "Fix version" assigned
- [x] issue "Status" is set to "In review"
- [x] PR labels are selected
- [x] FLP integration tests were ran successful

On the environment details page, mimic the basic panel from new environment with radio buttons to be disabled.
image

### CODE REVIEW

**Comment by awegrzyn** [comment]
Hi,
1. Is there any reason to pollute UI with "disabled" buttons, maybe simple value `ON`, `OFF`, etc would be enough? @vascobarroso ?
2. I think host list could be formatted as well? Eg. just comma separated instead of JSON array dump.

**Comment by graduta** [comment]
> Hi,
> 
>     1. Is there any reason to pollute UI with "disabled" buttons, maybe simple value `ON`, `OFF`, etc would be enough? @vascobarroso ?

The initial proposal was the use of values but after evaluation it was requested to use radio buttons as it is providing a more intuitive and easy to read form;

> 
>     2. I think host list could be formatted as well? Eg. just comma separated instead of JSON array dump.

It is comma separated and parsed compared to the old version of it. Screenshot below
image
I left it on purpose between square brackets so that it can be easily understood core expects a list and copy-paste it if needed. 
I would not split the names on a new line or anything similar as that list can contain potentially 200 items and it will take a lot of space. But I could add a space or two between the items to improve readability

**Comment by awegrzyn** [comment]
> it was requested to use radio buttons as it is providing a more intuitive and easy to read form

I'd agree if we did allow to modify these values at some stage but we do not

> It is comma separated and parsed compared to the old version of it.

Ok, indeed, thanks !

**Comment by vascobarroso** [comment]
Concerning the radio buttons vs value display, what I wanted to avoid was the discrepancy between the labels and values used in the env creation page (e.g `QC: ON`) and in the env details page (e.g. `QC: false`). If we use the same thing in both pages, then indeed the radio buttons might be redundant and can be removed.

**Pull request merged**
