### PR TITLE
[OGUI-850] Remove end slash if exists

### PR DESCRIPTION
**Pull request by graduta**
#### I have JIRA issue created
- [x] branch and/or PR name(s) includes JIRA ID
- [x] issue has "Fix version" assigned
- [x] issue "Status" is set to "In review"
- [x] PR labels are selected
- [] FLP integration tests were ran successful

Following `AliECS` changes, worfklow may or may not contain a trailing slash.
Ensure that the URL is properly built in both cases

### CODE REVIEW

**Review by awegrzyn — APPROVED** [review]
Ok for me but IMO this should be handled on the core side.

**Comment by graduta** [comment]
> Ok for me but IMO this should be handled on the core side.

I think it should still be on our side. I might have explained it a bit wrong. Please find below a more detailed explanation. 

This is not a change to remove the `/` at the end of the URL we send to core. 
We build the `workflow-URL` on our side from: `repository`, `worfklow` and `revision`.

Before we were getting from `Core`: `<name_of_repository>/` but now the slash was removed so instead of building a proper URL `repository/revision@workflow` we were sending to core `repositoryrevision@workflow`.

**Comment by awegrzyn** [comment]
Ok thx for explanation, maybe `path.join` or similar could be used?

**Comment by graduta** [comment]
> Ok thx for explanation, maybe `path.join` or similar could be used?

I think `path.join()` is a method from the module in NodeJS `path`. 
The URL selection and editing happens on the client side

**Pull request merged**
