### PR TITLE
[WIP] Added QCG frontend tests

### PR DESCRIPTION
**Pull request by vladimirkosmala**

### CODE REVIEW

**Comment by vladimirkosmala** [comment]
Here are some basic tests using chrome headless.
Run `npm start test/test-config.js`
Run `npm run mocha`

**Comment by awegrzyn** [comment]
It looks really nice, I assume I need to start chrome manually?
I will try to add it to travis.

**Comment by awegrzyn** [comment]
Ok so on my machine 3 are passing and 4 failing

**Comment by vladimirkosmala** [comment]
Could you post the output?
I changed command to start server in addition to tests.

`npm run mocha`

**Comment by awegrzyn** [comment]
Now the problem is that mocha tests start before the server is present therefore they fail due to connection refused

**Comment by awegrzyn** [comment]
Okay after b9ecd61 everything works!

**Comment by awegrzyn** [comment]
Ok it works on travis. Do you think we can use `config-default.js` instead of `test/test-config.js`?
Hostname and port in `test/mocha-index.js` can be parametrised with `${config.http.hostname}` and `${config.http.port}`.

**Pull request merged**
